### Sign In
POST http://localhost:8080/auth/signIn
Content-Type: application/json

{
	"username": "imposter",
	"password": "intmain()"
}


### Signup
POST http://localhost:8080/auth/signUp
Content-Type: application/json

{
	"username": "imposter",
	"password": "intmain()",
	"fName": "Aquib imposter",
	"lName": "Alam imposter",
	"email": "imposter399@gmail.com"
}

### Verify OTP
POST http://localhost:8080/auth/verifyOtp
Content-Type: application/json

{
	"email":"imposter399@gmail.com",
	"otp": 426568
}
