### Sign In
POST http://localhost:8080/auth/signIn
Content-Type: application/json

{
	"username": "abc123",
	"password": "intmain()"
}


### Signup
POST http://localhost:8080/auth/signUp
Content-Type: application/json

{
	"username": "aquib399",
	"password": "intmain()",
	"fName": "aquib",
	"lName": "alam",
	"email": "aquibalam399@gmail.com"
}

### Verify OTP
POST http://localhost:8080/auth/verifyOtp
Content-Type: application/json

{
	"email":"example@gmail.com",
	"otp":371652
}
