###
get http://localhost:8080/api/profile/getProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMDE5NTA0fQ.0sM5-uy0k4lrX27ns--wZdiqe2HZ4q4eMCWkfk8QmNQ
