### Get profile
GET http://localhost:8080/api/profile/getProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTExNjcwLCJleHAiOjE3MDQ0MDc2NzB9.sz6ZrwsRXxd-SoBwxI9wCNUDnhBjbVzhZb-V2nsubak

### Edit profile
POST http://localhost:8080/api/profile/editProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTExNjcwLCJleHAiOjE3MDQ0MDc2NzB9.sz6ZrwsRXxd-SoBwxI9wCNUDnhBjbVzhZb-V2nsubak

{ 
	"newPassword":"intmain()",
	"oldPassword":"aquibalam123",
	"fName":"Aquib", 
	"lName":"Alam"
}