### Add schedule
POST http://localhost:8080/api/schedule/addSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTAwMzY0fQ.UGb3aKDxnIDH4tgqd664CbNhWZ-CDFo-2qD7nMd5_E8

{	
	"title": "title 1",
	"description": "description 1",
	"time": "time 1",
	"type": "type 1"
}


### Get all schedule
GET http://localhost:8080/api/schedule/getAllSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTAwMzY0fQ.UGb3aKDxnIDH4tgqd664CbNhWZ-CDFo-2qD7nMd5_E8


### Delete schedule
POST http://localhost:8080/api/schedule/deleteSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTAwMzY0fQ.UGb3aKDxnIDH4tgqd664CbNhWZ-CDFo-2qD7nMd5_E8

{
	"id":"65835065f2bca9141583eda4"
}

### Edit schedule
POST http://localhost:8080/api/schedule/editSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTAwMzY0fQ.UGb3aKDxnIDH4tgqd664CbNhWZ-CDFo-2qD7nMd5_E8

{
	"id":"65835704cee9ff95649ad681",
	"title": "title edited",
	"description": "description edited",
	"time": "time edited",
	"type": "type edited"
}


### Set status 
POST http://localhost:8080/api/schedule/setScheduleStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTAwMzY0fQ.UGb3aKDxnIDH4tgqd664CbNhWZ-CDFo-2qD7nMd5_E8

{
	"id":"6583507cf2bca9141583edb0"
}




###Imposter
POST http://localhost:8080/api/schedule/deleteSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImltcG9zdGVyIiwiaWF0IjoxNzAzMTA0NzYyfQ.aNml4lExDB18PiDPe2zkSzpf027B0hbHSWvbDy9vQfU

{
	"id":"6583507cf2bca9141583edb0"
}

