### Add schedule
POST http://localhost:8080/api/schedule/addSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTA4NzkzLCJleHAiOjE3MDMxMDg5NzN9.9BIRqZUF028IidFKDSa5_ZRhn9TPjV7SOxyKiC6H16c

{	
	"title": "Go to school",
	"description": "Have breakfast and lunch",
	"time": "9PM",
	"type": "daily"
}


### Get all schedule
GET http://localhost:8080/api/schedule/getAllSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTA4NzkzLCJleHAiOjE3MDMxMDg5NzN9.9BIRqZUF028IidFKDSa5_ZRhn9TPjV7SOxyKiC6H16c

### Delete schedule
POST http://localhost:8080/api/schedule/deleteSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTA4NzkzLCJleHAiOjE3MDMxMDg5NzN9.9BIRqZUF028IidFKDSa5_ZRhn9TPjV7SOxyKiC6H16c
{
	"id":"65835065f2bca9141583eda4"
}

### Edit schedule
POST http://localhost:8080/api/schedule/editSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFxdWliMzk5IiwiaWF0IjoxNzAzMTA4NzkzLCJleHAiOjE3MDMxMDg5NzN9.9BIRqZUF028IidFKDSa5_ZRhn9TPjV7SOxyKiC6H16c
{
	"id":"65835704cee9ff95649ad683",
	"title": "title edited",
	"description": "description edited",
	"time": "time edited",
	"type": "type edited"
}


### Set status 
POST http://localhost:8080/api/schedule/setScheduleStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImltcG9zdGVyIiwiaWF0IjoxNzAzMTA4NTUwLCJleHAiOjE3MDMxMDg2NzB9.Q-TPAkPBtUoRbix2I1w-kIiWZNXeiiLe4aVwdxTMhOc
{
	"id":"6583507cf2bca9141583edb0"
}




###Imposter
POST http://localhost:8080/api/schedule/deleteSchedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImltcG9zdGVyIiwiaWF0IjoxNzAzMTA4NTUwLCJleHAiOjE3MDMxMDg2NzB9.Q-TPAkPBtUoRbix2I1w-kIiWZNXeiiLe4aVwdxTMhOc

{
	"id":"6583507cf2bca9141583edb0"
}

